# Generated by Django 3.2.6 on 2021-08-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.AlterField(
            model_name='city',
            name='cityName',
            field=models.CharField(help_text='Enter the name of city whose weather report you want', max_length=200, primary_key=True, serialize=False),
        ),
    ]
