# Generated by Django 3.2.6 on 2021-08-07 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0002_auto_20210807_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='id',
            field=models.BigAutoField(auto_created=True,  primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='cityName',
            field=models.CharField(help_text='Enter the name of city whose weather report you want', max_length=200),
        ),
    ]

# default=django.utils.timezone.now,