# Generated by Django 3.2.6 on 2021-08-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0003_auto_20210807_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cityName',
            field=models.CharField(max_length=200),
        ),
    ]
